import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/payload/globals/header/component";
import { Footer } from "@/payload/globals/footer/component";
import localFont from "next/font/local";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const abcDiatype = localFont({
  variable: "--font-abc-diatype",
  src: [
    {
      path: "../../public/fonts/ABCDiatypeExtended-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/ABCDiatypeExtended-Medium.otf",
      weight: "500",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${abcDiatype.variable} font-sans antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
